<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class QuestionsSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $questions = [
            'If money was to be "tight", could you keep to a budget?',
            'Without being unrealistic, do you consider yourself to be an optimist?',
            'In financial matters, can you confidently plan (as opposed to worrying about such things)?',
            'Do you feel comfortable if someone else has to do something you would otherwise be responsible for?',
            'Do you like to get involved in the running of things?',
            'When wanting to do something, do you feel that the opinions of others leave you inhibited or constrained?',
            'Would you say that you are objective, but fair in your dealings with others?',
            'Do you frequently feel compelled to justify your actions or explain yourself in the face of mild criticism?',
            'Would you say you are usually polite?',
            'Are you short of friends?',
            'Do you make thoughtless remarks or accusations which later you regret?',
            'When others are getting rattled, do you remain fairly composed?',
            'Do you browse through railway timetables, directories, or dictionaries just for pleasure?',
            'When asked to make a decision, would you be swayed by your like or dislike of the personality involved?',
            'Do you intend two or less children in your family even though your health and income will permit more?',

            'Do you get occasional twitches of your muscles, when there is no logical reason for it?',
            'Do you prefer to be in a position where you have the responsibility of making decisions?',
            'Are your actions considered unpredictable by other people?',
            'Do you consider more money should be spent on social security?',
            'Do other people interest you a lot?',
            'Is your voice varied in pitch, rather than monotonous?',
            'Do you normally let the other person start the conversation?',
            'Are you readily interested in other people\'s conversations?',
            'Would the idea of inflicting pain on game, small animals or fish prevent you from hunting or fishing?',
            'Are you often impulsive in your behavior?',
            'Do you speak slowly?',
            'Are you often concerned about the need to protect your health?',
            'Does an unexpected action cause your muscles to twitch?',
            'Are you normally considerate in your demands on your employees, relatives, or pupils?',
            'Do you consider that you could give a valid "snap judgment"?',

            'Do any past failures still worry you?',
            'Do you find yourself being extra-active for periods lasting several days?',
            'Do you resent the efforts of others to tell you what to do?',
            'Is it normally easy for you to "own up and take the blame"?',
            'Do you have a small circle of close friends, rather than a large number of friends, speaking acquaintances?',
            'Is your life a constant struggle for survival?',
            'Do you often sing or whistle just for the fun of it?',
            'Are you considered warm-hearted by your friends?',
            'Would you rather give orders than take them?',
            'Do you enjoy telling people the latest scandal about your associates?',
            'Could you agree to "strict discipline"?',
            'Does the idea of having to make a complete new start cause you little concern?',
            'Do you make efforts to get others to laugh and smile?',
            'Do you find it difficult to express your emotions?',
            'Do you refrain from complaining when the other person is late for an appointment?',

            'Are you sometimes considered by others a "spoilsport"?',
            'Do you consider there are other people who are definitely unfriendly toward you and work against you?',
            'Would you admit you were wrong just to "keep the peace"?',
            'Do you have only a few people of whom you are really fond?',
            'Are you rarely happy, unless you have a special reason?',
            'Do you "circulate around" at a social gathering?',
            'Do you take reasonable precaution to prevent accidents?',
            'Does the idea of talking in front of people make you nervous?',
            'If you saw an article in a shop obviously mistakenly marked lower than its correct price, would you try to get it at that price?',
            'Do you often feel that people are looking at you or talking about you behind your back?',
            'Are you "always getting into trouble"?',
            'Have you any particular hate or fear?',
            'Do you prefer to be a participant in an active sport, rather than a spectator?',
            'Do you find it easy to be impartial?',
            'Have you a definitely set standard of courteous behavior in front of other members of your family?',

            'Can you "start the ball rolling" at a social gathering?',
            'Would you "buy on credit" with the hope that you can keep up the payments?',
            'Do you get an after-reaction when something unexpected such as an accident or other disturbing incident takes place?',
            'Do you consider the good of all concerned rather than your own personal advantages?',
            'When hearing a lecturer, do you sometimes experience the idea that the speaker is referring entirely to you?',
            'Does "external noise" rarely interfere with your concentration?',
            'Are you normally "up-to-date" on everyday and current affairs?',
            'Can you confidently plan and work towards carrying out an event in six months time?',
            'Do you consider the modern "prisons without bars" system doomed to failure?',
            'Do you tend to be careless?',
            'Do you ever get a "dreamlike" feeling toward life when it all seems unreal?',
            'Do you speedily recover from the effects of bad news?',
            'When you criticize - do you at the same time try to encourage?',
            'Are you normally considered "cold"?',
            'Are your opinions insufficiently important to tell other people?',

            'Are you so self-assured that it sometimes annoys others?',
            'Do you keep "close contact" on articles of yours which you have loaned to friends?',
            'Do you enjoy activities of your own choosing?',
            'Does emotional music have quite an effect on you?',
            'Do you completely condemn a person because he is a rival or opponent in some aspect of your relations with him?',
            'Do you often "sit and think" about death, sickness, pain and sorrow?',
            'Are you perturbed at the idea of loss of dignity?',
            'Are you always collecting things which "might be useful"?',
            'Would you criticize faults and point out the bad points on someone else\'s character or handiwork?',
            'Are you openly appreciative of beautiful things?',
            'Do you sometimes give away articles which strictly speaking do not belong to you?',
            'Do you greet people enthusiastically?',
            'Do you often ponder on previous misfortunes?',
            'Are you sometimes considered forceful in your actions or opinions?',
            'Do you accept criticism easily and without resentment?',

            'Are you usually undisturbed by "noises off" when you are trying to rest?',
            'Are you likely to be jealous?',
            'Do you tend to put off doing things and then discover it is too late?',
            'Do you prefer to abide by the wishes of others rather than seek to have your own way?',
            'Do you find it easy to get yourself started on a project?',
            'Do you bite your fingernails or chew the end of your pencil?',
            'Do you "turn up the volume" of your emotions just to create an effect?',
            'If we were invading another country, would you feel sympathetic towards conscientious objectors in this country?',
            'Are there some things about yourself on which you are touchy?',
            'Do you have few interests and activities that are your own choice?',
            'Do you ever get a single thought which hangs around for days?',
            'Are you a slow eater?',
            'Can you be a stabilizing influence when others get panicky?',
            'Would you stop and find out whether a person needed help even though they had not directly asked you for it?',
            'Are you prejudiced in favor of your own school, college, club or team, etc.?',

            'Do you pay your debts and keep your promises when it is possible?',
            'Do you sleep well?',
            'Would you use corporal punishment on a child aged ten if it refused to obey you?',
            'Do you prefer to take a passive role in any club or organization to which you belong?',
            'Are you logical and scientific in your thinking?',
            'Does the youth of today have more opportunity than that of a generation ago?',
            'Do you throw things away only to discover that you need them later?',
            'Would you give up easily on a given course if it were causing you a considerable amount of inconvenience?',
            'Do you "wax enthusiastic" about only a few subjects?',
            'Do you rarely suspect the actions of others?',
            'Do you sometimes wonder if anyone really cares about you?',
            'Do you turn down responsibility because you doubt your fitness to cope?',
            'Do you sometimes feel compelled to repeat some interesting item or tidbit?',
            'Do you tend to exaggerate a justifiable grievance?',
            'Is your facial expression typically set rather than varied?',

            'Do you usually need to justify or back up an opinion once stated?',
            'Do you openly and sincerely admire beauty in other people?',
            'Would it take a definite effort on your part to consider the subject of suicide?',
            'Would you consider yourself energetic in your attitude toward life?',
            'Would a disagreement affect your general relationship with another person?',
            'Does a minor failure on your part rarely trouble you?',
            'Do you sometimes feel that you talk too much?',
            'Do you smile much?',
            'Are you easily pleased?',
            'When met with direct opposition do you normally give in rather than seek to have your own way?',
            'Provided the distance were not too great, would you still prefer to ride rather than walk?',
            'Do noises such as the wind or a "house settling down" ever disturbe you?',
            'Would you say that your experience, occupation or training influence your opinions?',
            'Do you rarely make tactless blunders?',
            'Are you suspicious of people who ask to borrow money from you?',

            'Are your decisions swayed by personal interests?',
            'Can you get quite enthusiastic over "some simple little thing"?',
            'Do you frequently take action even though you know your own good judgment would indicate otherwise?',
            'Are you in favor of color bar and class distinction?',
            'Are you aware of any habitual physical mannerisms such as pulling your hair, nose, ears, or such like?',
            'Can you quickly adapt and make use of new conditions and situations even though they may be difficult?',
            'Do some noises "set your teeth on edge"?',
            'Can you see the other person\'s point of view when you wish to?',
            'Do you go to bed when you want to, rather than "by the clock"?',
            'Do the "petty foibles" of others make you impatient?',
            'Do children irritate you?',
            'Are you less talkative than your associates?',
            'Do you usually carry out assignments promptly and systematically?',
            'Would you assist a fellow traveler rather than leave it to the officials?',
            'When voting, do you consider the candidates and issues rather than voting for the same party every time?',

            'Do you frequently dwell on your past illnesses or painful experiences?',
            'Do you get very ill at ease in disordered surroundings?',
            'Do you usually criticize a film or show that you see or a book that you read?',
            'When recounting some amusing incident can you easily imitate the mannerisms or the dialect in the original incident?',
            'In subjects about which you are not expert, are your own ideas of sufficient importance as to tell others?',
            'Do you have a tendency to tidy up a disorder of somebody else\'s household?',
            'Can you accept defeat easily without the necessity of "swallowing your disappointment"?',
            'Do you often feel depressed?',
            'Are you ever ill at ease in the company of children?',
            'Do you get frustrated at not being able to do something rather than finding a substitute activity or system?',
            'Are you normally able to enter the spirit of things?',
            'Do you rarely express your grievances?',
            'Do you work in "spurts," being relatively inactive and then furiously active for a day or two?',
            'Does the number of uncompleted jobs you have on hand bother you?',
            'Do people enjoy being in your company?',

            'Could you allow someone to finish those "final two words" in a crossword puzzle without interfering?',
            'Do you consider the best points of most people and only rarely speak slightingly of them?',
            'Do you laugh or smile quite readily?',
            'Are you definite and emphatic in voice and manner?',
            'Do you reveal your emotions only to close friends if at all?',
            'Are your interests and fields of knowledge so important as to give little time for anything else?',
            'Where you see the need, do you like to start a new activities?',
            'Would you make the necessary actions to kill an animal in order to put it out of pain?',
            'Is it easy for you to relax?',
            'Do you have little regret on past misfortunes and failures?',
            'Does the idea of fear or apprehension give you a physical reaction?',
            'Can you trust the decision of your judgment in an emotional situation in which you are involved?',
            'Could someone else consider that you were really active?',
            'Do you find it easy to get started on a task that needs to be done?',
            'Do you think the "probation system" for criminals is, in principle, a good idea?',

            'Do you spend little or no time on needless worries?',
            'In a disagreement do you find it hard to understand how the other person fails to see your side?',
            'Do you cope with everyday problems of living quite well?',
            'Are you usually truthful to others?',
            'Would you rather "wait for something to happen" as opposed to you causing it?',
            'Do you spend too freely in relation to your income?',
            'Can you take a "calculated risk" without too much worry?',
            'If you were involved in an accident, would you really take the trouble to see that any damage you did was made good?',
            'Do others push you around?',
            'Do you make allowances for your friends where with others you might judge more severely?',
            'Do you often ponder over your own inferiority?',
            'Do people criticize you to others?',
            'Are you embarrassed by a hearty greeting such as a kiss, hug, or pat on the back, if done in public?',
            'Do you frequently not do something you want to do because of other people\'s desires?',
            'Are you sometimes convinced of the correctness of your opinions about a subject even though you are not an expert?',

            'Do you often find yourself "going off in all directions at once"?',
            'Do your acquaintances seem to think more of your abilities than you do?',
            'Is the idea of death or even reminders of death abhorrent to you?',
            'Having settled an argument out do you continue to feel disgruntled for a while?',
            'Are you friendly in voice, attitude, and expression?',
            'Does life seem rather vague and unreal to you?',
            'Do you often feel upset about the fate of war victims and political refugees?',
            'Do "mere acquaintances" appeal to you for aid or advice in their personal difficulties?',
            'If you lose an article, do you get the idea that "someone must have stolen or mislaid it"?',
            'If you thought that someone was suspicious of you, would you leave them to work it out rather than tackle them on the subject?',
            'Do you sometimes feel that your age is against you (too young or too old)?',
            'Do you have spells of being sad and depressed for no apparent reason?',
            'Do you do much grumbling about conditions you have to face in life?',
            'Do you tend to hide your feelings?',
            'Do you consider you have many warm friends?'
        ];

        $per_page = config('assessment.questions_per_page', 15);
        $number = 1;
        foreach ($questions as $question) {
            DB::table('questions')->insert([
                'question'   => $question,
                'number'     => $number,
                'group'      => floor(($number - 1) / $per_page) + 1,
                'created_at' => Carbon::now()
            ]);

            $number++;
        }
    }
}
