const mix = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

// mix.js('resources/assets/js/app.js', 'public/js')
//    .sass('resources/assets/sass/app.scss', 'public/css');

mix
  .combine(
    [
      "public/theme/assets/vendors/general/jquery/dist/jquery.min.js",
      "public/theme/assets/vendors/general/popper.js/dist/umd/popper.min.jss",
      "public/theme/assets/vendors/general/bootstrap/dist/js/bootstrap.min.js",
      "public/theme/assets/vendors/general/js-cookie/src/js.cookie.min.js",
      "public/theme/assets/vendors/general/moment/min/moment.min.js",
      "theme/assets/vendors/general/tooltip.js/dist/umd/tooltip.min.js",
      "public/theme/assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.min.js",
      "public/theme/assets/vendors/general/sticky-js/dist/sticky.min.js",
      "public/theme/assets/vendors/general/wnumb/wNumb.min.js",
      "public/theme/assets/vendors/general/jquery-form/dist/jquery.form.min.js",
      "public/theme/assets/vendors/general/block-ui/jquery.blockUI.min.js",
      "public/theme/assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",
      "public/theme/assets/vendors/custom/components/vendors/bootstrap-datepicker/init.min.js",
      "public/theme/assets/vendors/general/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js",
      "public/theme/assets/vendors/general/bootstrap-timepicker/js/bootstrap-timepicker.min.js",
      "public/theme/assets/vendors/custom/components/vendors/bootstrap-timepicker/init.js",
      "public/theme/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.js",
      "public/theme/assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js",
      "public/theme/assets/vendors/general/bootstrap-maxlength/src/bootstrap-maxlength.js",
      "public/theme/assets/vendors/custom/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js",
      "public/theme/assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.js",
      "public/theme/assets/vendors/general/bootstrap-switch/dist/js/bootstrap-switch.js",
      "public/theme/assets/vendors/custom/components/vendors/bootstrap-switch/init.js",
      "public/theme/assets/vendors/general/select2/dist/js/select2.full.js",
      "public/theme/assets/vendors/general/ion-rangeslider/js/ion.rangeSlider.js",
      "public/theme/assets/vendors/general/typeahead.js/dist/typeahead.bundle.js",
      "public/theme/assets/vendors/general/handlebars/dist/handlebars.js",
      "public/theme/assets/vendors/general/inputmask/dist/jquery.inputmask.bundle.js",
      "public/theme/assets/vendors/general/inputmask/dist/inputmask/inputmask.date.extensions.js",
      "public/theme/assets/vendors/general/inputmask/dist/inputmask/inputmask.numeric.extensions.js",
      "public/theme/assets/vendors/general/nouislider/distribute/nouislider.js",
      "public/theme/assets/vendors/general/owl.carousel/dist/owl.carousel.js",
      "public/theme/assets/vendors/general/autosize/dist/autosize.js",
      "public/theme/assets/vendors/general/clipboard/dist/clipboard.min.js",
      "public/theme/assets/vendors/general/dropzone/dist/dropzone.js",
      "public/theme/assets/vendors/general/summernote/dist/summernote.js",
      "public/theme/assets/vendors/general/markdown/lib/markdown.js",
      "public/theme/assets/vendors/general/bootstrap-markdown/js/bootstrap-markdown.js",
      "public/theme/assets/vendors/custom/components/vendors/bootstrap-markdown/init.js",
      "public/theme/assets/vendors/general/bootstrap-notify/bootstrap-notify.min.js",
      "public/theme/assets/vendors/custom/components/vendors/bootstrap-notify/init.js",
      "public/theme/assets/vendors/general/jquery-validation/dist/jquery.validate.js",
      "public/theme/assets/vendors/general/jquery-validation/dist/additional-methods.js",
      "public/theme/assets/vendors/custom/components/vendors/jquery-validation/init.js",
      "public/theme/assets/vendors/general/toastr/build/toastr.min.js",
      "public/theme/assets/vendors/general/raphael/raphael.js",
      "public/theme/assets/vendors/general/morris.js/morris.js",
      "public/theme/assets/vendors/general/chart.js/dist/Chart.bundle.js",
      "public/theme/assets/vendors/custom/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js",
      "public/theme/assets/vendors/custom/vendors/jquery-idletimer/idle-timer.min.js",
      "public/theme/assets/vendors/general/waypoints/lib/jquery.waypoints.js",
      "public/theme/assets/vendors/general/counterup/jquery.counterup.js",
      "public/theme/assets/vendors/general/es6-promise-polyfill/promise.min.js",
      "public/theme/assets/vendors/general/sweetalert2/dist/sweetalert2.min.js",
      "public/theme/assets/vendors/custom/components/vendors/sweetalert2/init.js",
      "public/theme/assets/vendors/general/jquery.repeater/src/lib.js",
      "public/theme/assets/vendors/general/jquery.repeater/src/jquery.input.js",
      "public/theme/assets/vendors/general/jquery.repeater/src/repeater.js",
      "public/theme/assets/vendors/general/dompurify/dist/purify.js",
      "public/theme/assets/demo/demo10/base/scripts.bundle.js",
      "public/theme/assets/vendors/custom/fullcalendar/fullcalendar.bundle.js",
    ],
    "public/js/global-mandatory-option-vender.js"
  )
  .minify(["public/js/global-mandatory-option-vender.js"])
  .combine(
    [
      "public/theme/assets/vendors/custom/gmaps/gmaps.js",
      "public/theme/assets/app/custom/general/dashboard.js",
      "public/theme/assets/app/bundle/app.bundle.js",
    ],
    "public/js/combine-js-one.js"
  )
  .minify(["public/js/combine-js-one.js"])
  .styles(
    [
      "public/theme/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css",
      "public/theme/assets/vendors/general/perfect-scrollbar/css/perfect-scrollbar.css",
      "public/theme/assets/vendors/general/tether/dist/css/tether.css",
      "public/theme/assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css",
      "public/theme/assets/vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css",
      "public/theme/assets/vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css",
      "public/theme/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.css",
      "public/theme/assets/vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css",
      "public/theme/assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css",
      "public/theme/assets/vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css",
      "public/theme/assets/vendors/general/select2/dist/css/select2.css",
      "public/theme/assets/vendors/general/ion-rangeslider/css/ion.rangeSlider.css",
      "public/theme/assets/vendors/general/nouislider/distribute/nouislider.css",
      "public/theme/assets/vendors/general/owl.carousel/dist/assets/owl.carousel.css",
      "public/theme/assets/vendors/general/owl.carousel/dist/assets/owl.theme.default.css",
      "public/theme/assets/vendors/general/dropzone/dist/dropzone.css",
      "public/theme/assets/vendors/general/summernote/dist/summernote.css",
      "public/theme/assets/vendors/general/bootstrap-markdown/css/bootstrap-markdown.min.css",
      "public/theme/assets/vendors/general/animate.css/animate.css",
      "public/theme/assets/vendors/general/toastr/build/toastr.css",
      "public/theme/assets/vendors/general/morris.js/morris.css",
      "public/theme/assets/vendors/general/sweetalert2/dist/sweetalert2.css",
      "public/theme/assets/vendors/general/socicon/css/socicon.css",
      "public/theme/assets/vendors/custom/vendors/line-awesome/css/line-awesome.css",
      "public/theme/assets/vendors/custom/vendors/flaticon/flaticon.css",
      "public/theme/assets/vendors/custom/vendors/flaticon2/flaticon.css",
      "public/theme/assets/vendors/custom/vendors/fontawesome5/css/all.min.css",
      "public/theme/assets/demo/demo10/base/style.bundle.css",
      "public/theme/assets/app/custom/login/login-v3.demo10.css",
      "public/css/custom-styles.css",
    ],
    "public/css/app.blade.css"
  );
